### PR TITLE
Browser tests

### PR DESCRIPTION
**Pull request by ArtskydJ**
Added browser tests.

### CODE REVIEW

**Comment by ArtskydJ** [comment]
If you merge #4 and #5, you'll probably have a merge conflict in the package.json because both PRs add devDependencies. If you merge one of the two, I can update the other PR/create a new PR.

**Comment by ArtskydJ** [comment]
(Whoops, accidentally hit "close and comment" instead of "comment")

**Comment by TehShrike** [comment]
Merge conflict! :-x

**Comment by ArtskydJ** [comment]
Closing in favor of #6!

**Pull request closed without merging**
