### PR TITLE
Unicode char in url

### PR DESCRIPTION
**Pull request by ArtskydJ**
Fix unicode characters in URL.

If you don't like the solution, you can just grab the failing tests.

### CODE REVIEW

**Comment by TehShrike** [comment]
Where was this string coming from?  Was it from the butler?  Or something higher-level, like the seoaas server?

That's where I'd like to fix it - wherever this string was coming from, I think it's doing something not quite right.

**Comment by ArtskydJ** [comment]
This module is only used in the butler. The seoaas server uses the butler.

If you do `butler.getPost(filenameWithUnicode, cb)` then it'll do `retrieval.getPost(filenameWithUnicode, cb)` if the post isn't cached.

I'm of the opinion that the encoding/decoding of the string should be implemented here. If it was implemented in the butler, then you'd have to decode URL-encoded strings for `noddity-fs-retrieval`.

**Comment by TehShrike** [comment]
Looks good to me!

**Comment by TehShrike** [comment]
Published as 1.5.2.

**Pull request merged**
